import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * EnterpriseModule1720000000000
 *
 * Creates all tables required by the Genie for Enterprise extension:
 *   - enterprise_profiles          : KYB-verified enterprise entities
 *   - enterprise_api_keys          : Machine-to-machine API credentials
 *   - multi_channel_configs        : External channel integrations
 *   - fulfillment_routing_rules    : Provider routing logic per entity/region/channel
 *   - fulfillment_tasks            : Per-order dispatch records
 *   - agentic_concierge_sessions   : Genie AI session threads per enterprise
 *   - agentic_concierge_messages   : Per-turn message log
 *
 * Design rules:
 *   - UUIDs for all PKs, generated by gen_random_uuid().
 *   - All new enum types are guarded with DO $$ BEGIN ... EXCEPTION WHEN duplicate_object.
 *   - soft-delete via deleted_at column (nullable timestamptz).
 *   - down() tears everything down cleanly in reverse dependency order.
 */
export class EnterpriseModule1720000000000 implements MigrationInterface {
  name = 'EnterpriseModule1720000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── Enums ──────────────────────────────────────────────────────────────
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "enterprise_type_enum" AS ENUM (
          'corporation', 'streaming_platform', 'record_label', 'delivery_network',
          'food_aggregator', 'marketplace', 'qsr_chain', 'financial_institution', 'other'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "enterprise_status_enum" AS ENUM (
          'pending', 'active', 'suspended', 'terminated'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "api_key_permission_enum" AS ENUM (
          'payments', 'orders', 'products', 'fulfillment', 'eplay', 'analytics',
          'multi_channel', 'concierge', 'facilitator', 'all'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "channel_type_enum" AS ENUM (
          'shopify', 'walmart', 'amazon', 'magento', 'woocommerce', 'custom', 'pos', 'marketplace'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "channel_sync_status_enum" AS ENUM (
          'idle', 'syncing', 'error', 'paused'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "fulfillment_provider_enum" AS ENUM (
          'genie_live', 'uber_direct', 'amazon_mcf', 'glovo', 'doordash_drive', 'custom'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "fulfillment_status_enum" AS ENUM (
          'pending', 'dispatched', 'in_transit', 'delivered', 'failed', 'cancelled'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "concierge_session_status_enum" AS ENUM (
          'active', 'closed', 'handoff'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "message_role_enum" AS ENUM (
          'user', 'assistant', 'system'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$
    `);

    // ── enterprise_profiles ────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "enterprise_profiles" (
        "id"                    UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"             UUID        NOT NULL,
        "enterprise_type"       "enterprise_type_enum" NOT NULL,
        "status"                "enterprise_status_enum" NOT NULL DEFAULT 'pending',
        "legal_name"            VARCHAR(500) NOT NULL,
        "tax_id"                VARCHAR(100),
        "licence_document_url"  TEXT,
        "verified"              BOOLEAN     NOT NULL DEFAULT false,
        "enabled_pathways"      JSONB       NOT NULL DEFAULT '[]',
        "settings"              JSONB,
        "webhook_url"           VARCHAR(1000),
        "staff_seat_fee_usd"    NUMERIC(10,4) NOT NULL DEFAULT 4,
        "per_tx_fee_qp"         NUMERIC(10,6) NOT NULL DEFAULT 0.02,
        "parent_enterprise_id"  UUID,
        "is_facilitator"        BOOLEAN     NOT NULL DEFAULT false,
        "qp_issuance_cap"       NUMERIC(18,4),
        "created_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"            TIMESTAMPTZ,
        CONSTRAINT "PK_enterprise_profiles" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_enterprise_profiles_entity_id" ON "enterprise_profiles" ("entity_id")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_enterprise_profiles_status" ON "enterprise_profiles" ("status")`);

    // ── enterprise_api_keys ────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "enterprise_api_keys" (
        "id"            UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"     UUID        NOT NULL,
        "key_hash"      VARCHAR(255) NOT NULL,
        "key_prefix"    VARCHAR(20)  NOT NULL,
        "label"         VARCHAR(200) NOT NULL,
        "permissions"   JSONB        NOT NULL DEFAULT '[]',
        "is_active"     BOOLEAN      NOT NULL DEFAULT true,
        "expires_at"    TIMESTAMPTZ,
        "ip_whitelist"  JSONB        NOT NULL DEFAULT '[]',
        "last_used_at"  TIMESTAMPTZ,
        "created_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
        "updated_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
        "deleted_at"    TIMESTAMPTZ,
        CONSTRAINT "PK_enterprise_api_keys" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_enterprise_api_keys_entity_id" ON "enterprise_api_keys" ("entity_id")`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "UQ_enterprise_api_keys_key_hash" ON "enterprise_api_keys" ("key_hash") WHERE "deleted_at" IS NULL`);

    // ── multi_channel_configs ──────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "multi_channel_configs" (
        "id"            UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"     UUID        NOT NULL,
        "channel_type"  "channel_type_enum" NOT NULL,
        "channel_name"  VARCHAR(200) NOT NULL,
        "credentials"   JSONB,
        "sync_status"   "channel_sync_status_enum" NOT NULL DEFAULT 'idle',
        "last_synced_at" TIMESTAMPTZ,
        "last_sync_error" TEXT,
        "is_active"     BOOLEAN     NOT NULL DEFAULT true,
        "webhook_url"   VARCHAR(1000),
        "created_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"    TIMESTAMPTZ,
        CONSTRAINT "PK_multi_channel_configs" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_multi_channel_configs_entity_id" ON "multi_channel_configs" ("entity_id")`);

    // ── fulfillment_routing_rules ──────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "fulfillment_routing_rules" (
        "id"                  UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"           UUID        NOT NULL,
        "region_code"         VARCHAR(10),
        "channel_type"        VARCHAR(50),
        "primary_provider"    "fulfillment_provider_enum" NOT NULL,
        "fallback_providers"  JSONB       NOT NULL DEFAULT '[]',
        "priority"            INT         NOT NULL DEFAULT 100,
        "is_active"           BOOLEAN     NOT NULL DEFAULT true,
        "created_at"          TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"          TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"          TIMESTAMPTZ,
        CONSTRAINT "PK_fulfillment_routing_rules" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fulfillment_routing_rules_entity_id" ON "fulfillment_routing_rules" ("entity_id")`);

    // ── fulfillment_tasks ──────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "fulfillment_tasks" (
        "id"                    UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"             UUID        NOT NULL,
        "order_id"              UUID,
        "provider"              "fulfillment_provider_enum" NOT NULL,
        "status"                "fulfillment_status_enum" NOT NULL DEFAULT 'pending',
        "tracking_id"           VARCHAR(500),
        "estimated_delivery_at" TIMESTAMPTZ,
        "provider_payload"      JSONB,
        "failure_reason"        TEXT,
        "created_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"            TIMESTAMPTZ,
        CONSTRAINT "PK_fulfillment_tasks" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fulfillment_tasks_entity_id" ON "fulfillment_tasks" ("entity_id")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fulfillment_tasks_order_id" ON "fulfillment_tasks" ("order_id")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fulfillment_tasks_status" ON "fulfillment_tasks" ("status")`);

    // ── agentic_concierge_sessions ─────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "agentic_concierge_sessions" (
        "id"            UUID        NOT NULL DEFAULT gen_random_uuid(),
        "entity_id"     UUID        NOT NULL,
        "end_user_id"   VARCHAR(500) NOT NULL,
        "status"        "concierge_session_status_enum" NOT NULL DEFAULT 'active',
        "topic"         VARCHAR(500),
        "context"       JSONB,
        "created_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"    TIMESTAMPTZ,
        CONSTRAINT "PK_agentic_concierge_sessions" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_agentic_concierge_sessions_entity_id" ON "agentic_concierge_sessions" ("entity_id")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_agentic_concierge_sessions_end_user_id" ON "agentic_concierge_sessions" ("end_user_id")`);

    // ── agentic_concierge_messages ─────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "agentic_concierge_messages" (
        "id"                UUID        NOT NULL DEFAULT gen_random_uuid(),
        "session_id"        UUID        NOT NULL,
        "role"              "message_role_enum" NOT NULL,
        "content"           TEXT        NOT NULL,
        "detected_intent"   VARCHAR(100),
        "intent_confidence" FLOAT,
        "metadata"          JSONB,
        "created_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"        TIMESTAMPTZ,
        CONSTRAINT "PK_agentic_concierge_messages" PRIMARY KEY ("id"),
        CONSTRAINT "FK_agentic_concierge_messages_session"
          FOREIGN KEY ("session_id") REFERENCES "agentic_concierge_sessions" ("id")
          ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_agentic_concierge_messages_session_id" ON "agentic_concierge_messages" ("session_id")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Messages first (FK dependency)
    await queryRunner.query(`DROP TABLE IF EXISTS "agentic_concierge_messages"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "agentic_concierge_sessions"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "fulfillment_tasks"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "fulfillment_routing_rules"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "multi_channel_configs"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "enterprise_api_keys"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "enterprise_profiles"`);

    await queryRunner.query(`DROP TYPE IF EXISTS "message_role_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "concierge_session_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "fulfillment_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "fulfillment_provider_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "channel_sync_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "channel_type_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "api_key_permission_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "enterprise_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "enterprise_type_enum"`);
  }
}
